Added configMap in a dynamic style
owncloud-docker/helm-charts pull request #5
Opened 2022-09-23 14:02 UTC by d7oc

- Added configMap which allows to configure all values dynamically in YAML style in the values section which is then transferred to JSON inside a `config.php` file.
- This solution uses a symlink right now as oC10 cannot lookup subdirectories of the config directory yet. This solution has the downside that on container setup there might be a race condition which will heal itself after sometime. This happens if oC10 tries to read the symlink before the volume it refers to is mounted.

2022-09-23 14:06 UTC, d7oc commented
@xoxys I have removed the if conditions to disable the configMap dynamically. As this will not work right now. If everything is disabled the symlink still points to a file which is not existing and we have no means to delete the symlink again in this case. The only solution I see to fix this is adding a reverse config lookup in oC10.

2022-09-26 07:10 UTC, xoxys approved these changes

2022-09-26 07:41 UTC, xoxys requested changes
I would like to test it a bit more locally.

2022-09-26 08:53 UTC, xoxys approved these changes
I have slightly changed the default behavior:

- configExtra is empty by default now
- an empty configExtra is properly handled to create an empty PHP config snippet

2022-09-26 08:53 UTC, merged